version: '3'
services:
  node-app:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    volumes:
      - redis:/data

volumes:
  mongo-db:
  redis:
