version: '3'
services:
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - '3333:80'
      - '3333:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - node-app

  node-app:
    build: .
    image: ghcr.io/higorantonio/docker-nodejs-blog:1.0
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:7.0.2-alpine
    volumes:
      - redis:/data

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  mongo-db:
  redis:
