version: '3'
services:
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - '3333:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:7.0.2-alpine
    volumes:
      - redis:/data

volumes:
  mongo-db:
  redis:
