version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./src:/app/src:ro
    env_file:
      - ./.env.development
    command: yarn dev
